name: forecaster_toolbox
channels:
  - saravji
  - anaconda
  - defaults
dependencies:
  - python=3.6.4
  - flask
  - flask-cors
  - numpy
  - pandas
  - pmdarima
  - pymongo
  - pytest
  - requests
  - scikit-learn
  - waitress